name: Setup AWS
description: ""

inputs:
  aws-region:
    description: AWS region
    required: false
    default: us-east-1
  role-to-assume:
    description: Role to assume
    required: false
    default: ""
  profile:
    description: AWS profile to setup
    required: false
    default: public

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}

    - name: Configure AWS profile
      shell: bash
      run: |
        aws configure set region                "${{ inputs.aws-region }}" --profile "${{ inputs.profile }}"
        aws configure set aws_access_key_id     "${AWS_ACCESS_KEY_ID}"     --profile "${{ inputs.profile }}"
        aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}" --profile "${{ inputs.profile }}"
        aws configure set aws_session_token     "${AWS_SESSION_TOKEN}"     --profile "${{ inputs.profile }}"

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: "true"

    - name: Permission check
      if: failure()
      shell: bash
      run: "echo Did you add \"id-token: write\" to the permissions block?"
